List<AppIntlCountry> intlCountriesList = [
  AppIntlCountry(
    name: "Afghanistan",
    nameAr: 'أفغانستان',
    flag: "🇦🇫",
    code: "AF",
    dialCode: "93",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Åland Islands",
    nameAr: 'جزر أولاند',
    flag: "🇦🇽",
    code: "AX",
    dialCode: "358",
    minLength: 15,
    maxLength: 15,
  ),
  AppIntlCountry(
    name: "Albania",
    nameAr: 'ألبانيا',
    flag: "🇦🇱",
    code: "AL",
    dialCode: "355",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Algeria",
    nameAr: 'الجزائر',
    flag: "🇩🇿",
    code: "DZ",
    dialCode: "213",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "American Samoa",
    nameAr: 'ساموا الأمريكية',
    flag: "🇦🇸",
    code: "AS",
    dialCode: "1684",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Andorra",
    nameAr: 'أندورا',
    flag: "🇦🇩",
    code: "AD",
    dialCode: "376",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Angola",
    nameAr: 'أنغولا',
    flag: "🇦🇴",
    code: "AO",
    dialCode: "244",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Anguilla",
    nameAr: 'أنغويلا',
    flag: "🇦🇮",
    code: "AI",
    dialCode: "1264",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Antarctica",
    nameAr: 'القارة القطبية الجنوبية',
    flag: "🇦🇶",
    code: "AQ",
    dialCode: "672",
    minLength: 6,
    maxLength: 6,
  ),
  AppIntlCountry(
    name: "Antigua and Barbuda",
    nameAr: 'أنتيغوا وباربودا',
    flag: "🇦🇬",
    code: "AG",
    dialCode: "1268",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Argentina",
    nameAr: 'الأرجنتين',
    flag: "🇦🇷",
    code: "AR",
    dialCode: "54",
    minLength: 12,
    maxLength: 12,
  ),
  AppIntlCountry(
    name: "Armenia",
    nameAr: 'أرمينيا',
    flag: "🇦🇲",
    code: "AM",
    dialCode: "374",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Aruba",
    nameAr: 'أروبا',
    flag: "🇦🇼",
    code: "AW",
    dialCode: "297",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Australia",
    nameAr: 'أستراليا',
    flag: "🇦🇺",
    code: "AU",
    dialCode: "61",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Austria",
    nameAr: 'النمسا',
    flag: "🇦🇹",
    code: "AT",
    dialCode: "43",
    minLength: 13,
    maxLength: 13,
  ),
  AppIntlCountry(
    name: "Azerbaijan",
    nameAr: 'أذربيجان',
    flag: "🇦🇿",
    code: "AZ",
    dialCode: "994",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Bahamas",
    nameAr: 'باهاماس',
    flag: "🇧🇸",
    code: "BS",
    dialCode: "1242",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Bahrain",
    nameAr: 'البحرين',
    flag: "🇧🇭",
    code: "BH",
    dialCode: "973",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Bangladesh",
    nameAr: 'بنغلاديش',
    flag: "🇧🇩",
    code: "BD",
    dialCode: "880",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Barbados",
    nameAr: 'باربادوس',
    flag: "🇧🇧",
    code: "BB",
    dialCode: "1246",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Belarus",
    nameAr: 'بيلاروس',
    flag: "🇧🇾",
    code: "BY",
    dialCode: "375",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Belgium",
    nameAr: 'بلجيكا',
    flag: "🇧🇪",
    code: "BE",
    dialCode: "32",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Belize",
    nameAr: 'بليز',
    flag: "🇧🇿",
    code: "BZ",
    dialCode: "501",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Benin",
    nameAr: 'بنين',
    flag: "🇧🇯",
    code: "BJ",
    dialCode: "229",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Bermuda",
    nameAr: 'برمودا',
    flag: "🇧🇲",
    code: "BM",
    dialCode: "1441",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Bhutan",
    nameAr: 'بوتان',
    flag: "🇧🇹",
    code: "BT",
    dialCode: "975",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Bolivia, Plurinational State of bolivia",
    nameAr: 'بوليفيا',
    flag: "🇧🇴",
    code: "BO",
    dialCode: "591",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Bosnia and Herzegovina",
    nameAr: 'البوسنة والهرسك',
    flag: "🇧🇦",
    code: "BA",
    dialCode: "387",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Botswana",
    nameAr: 'بوتسوانا',
    flag: "🇧🇼",
    code: "BW",
    dialCode: "267",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Bouvet Island",
    nameAr: 'جزيرة بوفيه',
    flag: "🇧🇻",
    code: "BV",
    dialCode: "47",
    minLength: 15,
    maxLength: 15,
  ),
  AppIntlCountry(
    name: "Brazil",
    nameAr: 'البرازيل',
    flag: "🇧🇷",
    code: "BR",
    dialCode: "55",
    minLength: 11,
    maxLength: 11,
  ),
  AppIntlCountry(
    name: "British Indian Ocean Territory",
    nameAr: 'إقليم المحيط الهندي البريطاني',
    flag: "🇮🇴",
    code: "IO",
    dialCode: "246",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Brunei Darussalam",
    nameAr: 'بروناي',
    flag: "🇧🇳",
    code: "BN",
    dialCode: "673",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Bulgaria",
    nameAr: 'بلغاريا',
    flag: "🇧🇬",
    code: "BG",
    dialCode: "359",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Burkina Faso",
    nameAr: 'بوركينا فاسو',
    flag: "🇧🇫",
    code: "BF",
    dialCode: "226",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Burundi",
    nameAr: 'بوروندي',
    flag: "🇧🇮",
    code: "BI",
    dialCode: "257",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Cambodia",
    nameAr: 'كمبوديا',
    flag: "🇰🇭",
    code: "KH",
    dialCode: "855",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Cameroon",
    nameAr: 'الكاميرون',
    flag: "🇨🇲",
    code: "CM",
    dialCode: "237",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Canada",
    nameAr: 'كندا',
    flag: "🇨🇦",
    code: "CA",
    dialCode: "1",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Cape Verde",
    nameAr: 'الرأس الأخضر',
    flag: "🇨🇻",
    code: "CV",
    dialCode: "238",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Cayman Islands",
    nameAr: 'جزر كايمان',
    flag: "🇰🇾",
    code: "KY",
    dialCode: "345",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Central African Republic",
    nameAr: 'جمهورية أفريقيا الوسطى',
    flag: "🇨🇫",
    code: "CF",
    dialCode: "236",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Chad",
    nameAr: 'تشاد',
    flag: "🇹🇩",
    code: "TD",
    dialCode: "235",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Chile",
    nameAr: 'تشيلي',
    flag: "🇨🇱",
    code: "CL",
    dialCode: "56",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "China",
    nameAr: 'الصين',
    flag: "🇨🇳",
    code: "CN",
    dialCode: "86",
    minLength: 12,
    maxLength: 12,
  ),
  AppIntlCountry(
    name: "Christmas Island",
    nameAr: 'جزيرة كريسماس',
    flag: "🇨🇽",
    code: "CX",
    dialCode: "61",
    minLength: 15,
    maxLength: 15,
  ),
  AppIntlCountry(
    name: "Cocos (Keeling) Islands",
    nameAr: 'جزر كوكوس',
    flag: "🇨🇨",
    code: "CC",
    dialCode: "61",
    minLength: 15,
    maxLength: 15,
  ),
  AppIntlCountry(
    name: "Colombia",
    nameAr: 'كولومبيا',
    flag: "🇨🇴",
    code: "CO",
    dialCode: "57",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Comoros",
    nameAr: 'جزر القمر',
    flag: "🇰🇲",
    code: "KM",
    dialCode: "269",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Cook Islands",
    nameAr: 'جزر كوك',
    flag: "🇨🇰",
    code: "CK",
    dialCode: "682",
    minLength: 5,
    maxLength: 5,
  ),
  AppIntlCountry(
    name: "Costa Rica",
    nameAr: 'كوستاريكا',
    flag: "🇨🇷",
    code: "CR",
    dialCode: "506",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Côte d'Ivoire",
    nameAr: 'ساحل العاج',
    flag: "🇨🇮",
    code: "CI",
    dialCode: "225",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Croatia",
    nameAr: 'كرواتيا',
    flag: "🇭🇷",
    code: "HR",
    dialCode: "385",
    minLength: 12,
    maxLength: 12,
  ),
  AppIntlCountry(
    name: "Cuba",
    nameAr: 'كوبا',
    flag: "🇨🇺",
    code: "CU",
    dialCode: "53",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Cyprus",
    nameAr: 'قبرص',
    flag: "🇨🇾",
    code: "CY",
    dialCode: "357",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Czech Republic",
    nameAr: 'جمهورية التشيك',
    flag: "🇨🇿",
    code: "CZ",
    dialCode: "420",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Denmark",
    nameAr: 'الدنمارك',
    flag: "🇩🇰",
    code: "DK",
    dialCode: "45",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Djibouti",
    nameAr: 'جيبوتي',
    flag: "🇩🇯",
    code: "DJ",
    dialCode: "253",
    minLength: 6,
    maxLength: 6,
  ),
  AppIntlCountry(
    name: "Dominica",
    nameAr: 'دومينيكا',
    flag: "🇩🇲",
    code: "DM",
    dialCode: "1767",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Dominican Republic",
    nameAr: 'جمهورية الدومينيكان',
    flag: "🇩🇴",
    code: "DO",
    dialCode: "1849",
    minLength: 12,
    maxLength: 12,
  ),
  AppIntlCountry(
    name: "Ecuador",
    nameAr: 'الإكوادور',
    flag: "🇪🇨",
    code: "EC",
    dialCode: "593",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Egypt",
    nameAr: 'مصر',
    flag: "🇪🇬",
    code: "EG",
    dialCode: "20",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "El Salvador",
    nameAr: 'السلفادور',
    flag: "🇸🇻",
    code: "SV",
    dialCode: "503",
    minLength: 11,
    maxLength: 11,
  ),
  AppIntlCountry(
    name: "Equatorial Guinea",
    nameAr: 'غينيا الاستوائية',
    flag: "🇬🇶",
    code: "GQ",
    dialCode: "240",
    minLength: 6,
    maxLength: 6,
  ),
  AppIntlCountry(
    name: "Eritrea",
    nameAr: 'إريتريا',
    flag: "🇪🇷",
    code: "ER",
    dialCode: "291",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Estonia",
    nameAr: 'إستونيا',
    flag: "🇪🇪",
    code: "EE",
    dialCode: "372",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Ethiopia",
    nameAr: 'إثيوبيا',
    flag: "🇪🇹",
    code: "ET",
    dialCode: "251",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Falkland Islands (Malvinas)",
    nameAr: 'جزر فوكلاند',
    flag: "🇫🇰",
    code: "FK",
    dialCode: "500",
    minLength: 5,
    maxLength: 5,
  ),
  AppIntlCountry(
    name: "Faroe Islands",
    nameAr: 'جزر فارو',
    flag: "🇫🇴",
    code: "FO",
    dialCode: "298",
    minLength: 6,
    maxLength: 6,
  ),
  AppIntlCountry(
    name: "Fiji",
    nameAr: 'فيجي',
    flag: "🇫🇯",
    code: "FJ",
    dialCode: "679",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Finland",
    nameAr: 'فنلندا',
    flag: "🇫🇮",
    code: "FI",
    dialCode: "358",
    minLength: 12,
    maxLength: 12,
  ),
  AppIntlCountry(
    name: "France",
    nameAr: 'فرنسا',
    flag: "🇫🇷",
    code: "FR",
    dialCode: "33",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "French Guiana",
    nameAr: 'غويانا الفرنسية',
    flag: "🇬🇫",
    code: "GF",
    dialCode: "594",
    minLength: 15,
    maxLength: 15,
  ),
  AppIntlCountry(
    name: "French Polynesia",
    nameAr: 'بولينزيا الفرنسية',
    flag: "🇵🇫",
    code: "PF",
    dialCode: "689",
    minLength: 6,
    maxLength: 6,
  ),
  AppIntlCountry(
    name: "French Southern Territories",
    nameAr: 'أراض فرنسية جنوبية وأنتارتيكية',
    flag: "🇹🇫",
    code: "TF",
    dialCode: "262",
    minLength: 15,
    maxLength: 15,
  ),
  AppIntlCountry(
    name: "Gabon",
    nameAr: 'الغابون',
    flag: "🇬🇦",
    code: "GA",
    dialCode: "241",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Gambia",
    nameAr: 'غامبيا',
    flag: "🇬🇲",
    code: "GM",
    dialCode: "220",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Georgia",
    nameAr: 'جورجيا',
    flag: "🇬🇪",
    code: "GE",
    dialCode: "995",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Germany",
    nameAr: 'ألمانيا',
    flag: "🇩🇪",
    code: "DE",
    dialCode: "49",
    minLength: 9,
    maxLength: 13,
  ),
  AppIntlCountry(
    name: "Ghana",
    nameAr: 'غانا',
    flag: "🇬🇭",
    code: "GH",
    dialCode: "233",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Gibraltar",
    nameAr: 'جبل طارق',
    flag: "🇬🇮",
    code: "GI",
    dialCode: "350",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Greece",
    nameAr: 'اليونان',
    flag: "🇬🇷",
    code: "GR",
    dialCode: "30",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Greenland",
    nameAr: 'جرينلاند',
    flag: "🇬🇱",
    code: "GL",
    dialCode: "299",
    minLength: 6,
    maxLength: 6,
  ),
  AppIntlCountry(
    name: "Grenada",
    nameAr: 'غرينادا',
    flag: "🇬🇩",
    code: "GD",
    dialCode: "1473",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Guadeloupe",
    nameAr: 'غوادلوب',
    flag: "🇬🇵",
    code: "GP",
    dialCode: "590",
    minLength: 15,
    maxLength: 15,
  ),
  AppIntlCountry(
    name: "Guam",
    nameAr: 'غوام',
    flag: "🇬🇺",
    code: "GU",
    dialCode: "1671",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Guatemala",
    nameAr: 'غواتيمالا',
    flag: "🇬🇹",
    code: "GT",
    dialCode: "502",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Guinea",
    nameAr: 'غينيا',
    flag: "🇬🇳",
    code: "GN",
    dialCode: "224",
    minLength: 8,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Guinea-Bissau",
    nameAr: 'غينيا بيساو',
    flag: "🇬🇼",
    code: "GW",
    dialCode: "245",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Guyana",
    nameAr: 'غيانا',
    flag: "🇬🇾",
    code: "GY",
    dialCode: "592",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Haiti",
    nameAr: 'هايتي',
    flag: "🇭🇹",
    code: "HT",
    dialCode: "509",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Heard Island and Mcdonald Islands",
    nameAr: 'جزيرة هيرد وجزر ماكدونالد',
    flag: "🇭🇲",
    code: "HM",
    dialCode: "672",
    minLength: 15,
    maxLength: 15,
  ),
  AppIntlCountry(
    name: "Holy See (Vatican City State)",
    nameAr: 'الكرسي الرسولي',
    flag: "🇻🇦",
    code: "VA",
    dialCode: "379",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Honduras",
    nameAr: 'هندوراس',
    flag: "🇭🇳",
    code: "HN",
    dialCode: "504",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Hong Kong",
    nameAr: 'هونغ كونغ',
    flag: "🇭🇰",
    code: "HK",
    dialCode: "852",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Hungary",
    nameAr: 'المجر',
    flag: "🇭🇺",
    code: "HU",
    dialCode: "36",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Iceland",
    nameAr: 'آيسلندا',
    flag: "🇮🇸",
    code: "IS",
    dialCode: "354",
    minLength: 7,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "India",
    nameAr: 'الهند',
    flag: "🇮🇳",
    code: "IN",
    dialCode: "91",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Indonesia",
    nameAr: 'إندونيسيا',
    flag: "🇮🇩",
    code: "ID",
    dialCode: "62",
    minLength: 13,
    maxLength: 13,
  ),
  AppIntlCountry(
    name: "Iran, Islamic Republic of Persian Gulf",
    nameAr: 'إيران',
    flag: "🇮🇷",
    code: "IR",
    dialCode: "98",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Iraq",
    nameAr: 'العراق',
    flag: "🇮🇶",
    code: "IQ",
    dialCode: "964",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Ireland",
    nameAr: 'جزيرة أيرلندا',
    flag: "🇮🇪",
    code: "IE",
    dialCode: "353",
    minLength: 7,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Isle of Man",
    nameAr: 'جزيرة مان',
    flag: "🇮🇲",
    code: "IM",
    dialCode: "44",
    minLength: 6,
    maxLength: 6,
  ),
  AppIntlCountry(
    name: "Israel",
    nameAr: 'اسرائيل',
    flag: "🇮🇱",
    code: "IL",
    dialCode: "972",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Italy",
    nameAr: 'إيطاليا',
    flag: "🇮🇹",
    code: "IT",
    dialCode: "39",
    minLength: 13,
    maxLength: 13,
  ),
  AppIntlCountry(
    name: "Jamaica",
    nameAr: 'جامايكا',
    flag: "🇯🇲",
    code: "JM",
    dialCode: "1876",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Japan",
    nameAr: 'اليابان',
    flag: "🇯🇵",
    code: "JP",
    dialCode: "81",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Jersey",
    nameAr: 'جيرزي',
    flag: "🇯🇪",
    code: "JE",
    dialCode: "44",
    minLength: 6,
    maxLength: 6,
  ),
  AppIntlCountry(
    name: "Jordan",
    nameAr: 'الأردن',
    flag: "🇯🇴",
    code: "JO",
    dialCode: "962",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Kazakhstan",
    nameAr: 'كازاخستان',
    flag: "🇰🇿",
    code: "KZ",
    dialCode: "7",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Kenya",
    nameAr: 'كينيا',
    flag: "🇰🇪",
    code: "KE",
    dialCode: "254",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Kiribati",
    nameAr: 'كيريباتي',
    flag: "🇰🇮",
    code: "KI",
    dialCode: "686",
    minLength: 5,
    maxLength: 5,
  ),
  AppIntlCountry(
    name: "Korea, Democratic People's Republic of Korea",
    nameAr: 'كوريا الشمالية',
    flag: "🇰🇵",
    code: "KP",
    dialCode: "850",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Korea, Republic of South Korea",
    nameAr: 'كوريا الجنوبية',
    flag: "🇰🇷",
    code: "KR",
    dialCode: "82",
    minLength: 11,
    maxLength: 11,
  ),
  AppIntlCountry(
    name: "Kosovo",
    nameAr: 'كوسوفو',
    flag: "🇽🇰",
    code: "XK",
    dialCode: "383",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Kuwait",
    nameAr: 'الكويت',
    flag: "🇰🇼",
    code: "KW",
    dialCode: "965",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Kyrgyzstan",
    nameAr: 'قيرغيزستان',
    flag: "🇰🇬",
    code: "KG",
    dialCode: "996",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Laos",
    nameAr: 'لاوس',
    flag: "🇱🇦",
    code: "LA",
    dialCode: "856",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Latvia",
    nameAr: 'لاتفيا',
    flag: "🇱🇻",
    code: "LV",
    dialCode: "371",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Lebanon",
    nameAr: 'لبنان',
    flag: "🇱🇧",
    code: "LB",
    dialCode: "961",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Lesotho",
    nameAr: 'ليسوتو',
    flag: "🇱🇸",
    code: "LS",
    dialCode: "266",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Liberia",
    nameAr: 'ليبيريا',
    flag: "🇱🇷",
    code: "LR",
    dialCode: "231",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Libyan Arab Jamahiriya",
    nameAr: 'الجماهيرية العربية الليبية الشعبية الاشتراكية العظمى',
    flag: "🇱🇾",
    code: "LY",
    dialCode: "218",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Liechtenstein",
    nameAr: 'ليختنشتاين',
    flag: "🇱🇮",
    code: "LI",
    dialCode: "423",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Lithuania",
    nameAr: 'ليتوانيا',
    flag: "🇱🇹",
    code: "LT",
    dialCode: "370",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Luxembourg",
    nameAr: 'لوكسمبورغ',
    flag: "🇱🇺",
    code: "LU",
    dialCode: "352",
    minLength: 11,
    maxLength: 11,
  ),
  AppIntlCountry(
    name: "Macao",
    nameAr: 'ماكاو',
    flag: "🇲🇴",
    code: "MO",
    dialCode: "853",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Macedonia",
    nameAr: 'مقدونيا',
    flag: "🇲🇰",
    code: "MK",
    dialCode: "389",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Madagascar",
    nameAr: 'مدغشقر',
    flag: "🇲🇬",
    code: "MG",
    dialCode: "261",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Malawi",
    nameAr: 'مالاوي',
    flag: "🇲🇼",
    code: "MW",
    dialCode: "265",
    minLength: 7,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Malaysia",
    nameAr: 'ماليزيا',
    flag: "🇲🇾",
    code: "MY",
    dialCode: "60",
    minLength: 11,
    maxLength: 11,
  ),
  AppIntlCountry(
    name: "Maldives",
    nameAr: 'المالديف',
    flag: "🇲🇻",
    code: "MV",
    dialCode: "960",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Mali",
    nameAr: 'مالي',
    flag: "🇲🇱",
    code: "ML",
    dialCode: "223",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Malta",
    nameAr: 'مالطا',
    flag: "🇲🇹",
    code: "MT",
    dialCode: "356",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Marshall Islands",
    nameAr: 'جزر مارشال',
    flag: "🇲🇭",
    code: "MH",
    dialCode: "692",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Martinique",
    nameAr: 'مارتينيك',
    flag: "🇲🇶",
    code: "MQ",
    dialCode: "596",
    minLength: 15,
    maxLength: 15,
  ),
  AppIntlCountry(
    name: "Mauritania",
    nameAr: 'موريتانيا',
    flag: "🇲🇷",
    code: "MR",
    dialCode: "222",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Mauritius",
    nameAr: 'موريشيوس',
    flag: "🇲🇺",
    code: "MU",
    dialCode: "230",
    minLength: 7,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Mayotte",
    nameAr: 'مايوت',
    flag: "🇾🇹",
    code: "YT",
    dialCode: "262",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Mexico",
    nameAr: 'المكسيك',
    flag: "🇲🇽",
    code: "MX",
    dialCode: "52",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Micronesia, Federated States of Micronesia",
    nameAr: 'ولايات ميكرونيسيا المتحدة',
    flag: "🇫🇲",
    code: "FM",
    dialCode: "691",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Moldova",
    nameAr: 'مولدوفا',
    flag: "🇲🇩",
    code: "MD",
    dialCode: "373",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Monaco",
    nameAr: 'موناكو',
    flag: "🇲🇨",
    code: "MC",
    dialCode: "377",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Mongolia",
    nameAr: 'منغوليا',
    flag: "🇲🇳",
    code: "MN",
    dialCode: "976",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Montenegro",
    nameAr: 'الجبل الأسود',
    flag: "🇲🇪",
    code: "ME",
    dialCode: "382",
    minLength: 12,
    maxLength: 12,
  ),
  AppIntlCountry(
    name: "Montserrat",
    nameAr: 'مونتسرات',
    flag: "🇲🇸",
    code: "MS",
    dialCode: "1664",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Morocco",
    nameAr: 'المغرب',
    flag: "🇲🇦",
    code: "MA",
    dialCode: "212",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Mozambique",
    nameAr: 'موزمبيق',
    flag: "🇲🇿",
    code: "MZ",
    dialCode: "258",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Myanmar",
    nameAr: 'ميانمار',
    flag: "🇲🇲",
    code: "MM",
    dialCode: "95",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Namibia",
    nameAr: 'ناميبيا',
    flag: "🇳🇦",
    code: "NA",
    dialCode: "264",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Nauru",
    nameAr: 'ناورو',
    flag: "🇳🇷",
    code: "NR",
    dialCode: "674",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Nepal",
    nameAr: 'نيبال',
    flag: "🇳🇵",
    code: "NP",
    dialCode: "977",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Netherlands",
    nameAr: 'هولندا',
    flag: "🇳🇱",
    code: "NL",
    dialCode: "31",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Netherlands Antilles",
    nameAr: 'جزر الأنتيل الهولندية',
    flag: "",
    code: "AN",
    dialCode: "599",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "New Caledonia",
    nameAr: 'كاليدونيا الجديدة',
    flag: "🇳🇨",
    code: "NC",
    dialCode: "687",
    minLength: 6,
    maxLength: 6,
  ),
  AppIntlCountry(
    name: "New Zealand",
    nameAr: 'نيوزيلندا',
    flag: "🇳🇿",
    code: "NZ",
    dialCode: "64",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Nicaragua",
    nameAr: 'نيكاراغوا',
    flag: "🇳🇮",
    code: "NI",
    dialCode: "505",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Niger",
    nameAr: 'النيجر',
    flag: "🇳🇪",
    code: "NE",
    dialCode: "227",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Nigeria",
    nameAr: 'نيجيريا',
    flag: "🇳🇬",
    code: "NG",
    dialCode: "234",
    minLength: 10,
    maxLength: 11,
  ),
  AppIntlCountry(
    name: "Niue",
    nameAr: 'نييوي',
    flag: "🇳🇺",
    code: "NU",
    dialCode: "683",
    minLength: 4,
    maxLength: 4,
  ),
  AppIntlCountry(
    name: "Norfolk Island",
    nameAr: 'جزيرة نورفولك',
    flag: "🇳🇫",
    code: "NF",
    dialCode: "672",
    minLength: 15,
    maxLength: 15,
  ),
  AppIntlCountry(
    name: "Northern Mariana Islands",
    nameAr: 'جزر ماريانا الشمالية',
    flag: "🇲🇵",
    code: "MP",
    dialCode: "1670",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Norway",
    nameAr: 'النرويج',
    flag: "🇳🇴",
    code: "NO",
    dialCode: "47",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Oman",
    nameAr: 'عمان',
    flag: "🇴🇲",
    code: "OM",
    dialCode: "968",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Pakistan",
    nameAr: 'باكستان',
    flag: "🇵🇰",
    code: "PK",
    dialCode: "92",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Palau",
    nameAr: 'بالاو',
    flag: "🇵🇼",
    code: "PW",
    dialCode: "680",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Palestinian Territory, Occupied",
    nameAr: 'فلسطين',
    flag: "🇵🇸",
    code: "PS",
    dialCode: "970",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Panama",
    nameAr: 'بنما',
    flag: "🇵🇦",
    code: "PA",
    dialCode: "507",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Papua New Guinea",
    nameAr: 'بابوا غينيا الجديدة',
    flag: "🇵🇬",
    code: "PG",
    dialCode: "675",
    minLength: 11,
    maxLength: 11,
  ),
  AppIntlCountry(
    name: "Paraguay",
    nameAr: 'باراغواي',
    flag: "🇵🇾",
    code: "PY",
    dialCode: "595",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Peru",
    nameAr: 'بيرو',
    flag: "🇵🇪",
    code: "PE",
    dialCode: "51",
    minLength: 11,
    maxLength: 11,
  ),
  AppIntlCountry(
    name: "Philippines",
    nameAr: 'الفلبين',
    flag: "🇵🇭",
    code: "PH",
    dialCode: "63",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Pitcairn",
    nameAr: 'جزر بيتكيرن',
    flag: "🇵🇳",
    code: "PN",
    dialCode: "64",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Poland",
    nameAr: 'بولندا',
    flag: "🇵🇱",
    code: "PL",
    dialCode: "48",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Portugal",
    nameAr: 'البرتغال',
    flag: "🇵🇹",
    code: "PT",
    dialCode: "351",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Puerto Rico",
    nameAr: 'بورتوريكو',
    flag: "🇵🇷",
    code: "PR",
    dialCode: "1939",
    minLength: 15,
    maxLength: 15,
  ),
  AppIntlCountry(
    name: "Qatar",
    nameAr: 'قطر',
    flag: "🇶🇦",
    code: "QA",
    dialCode: "974",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Romania",
    nameAr: 'رومانيا',
    flag: "🇷🇴",
    code: "RO",
    dialCode: "40",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Russia",
    nameAr: 'روسيا',
    flag: "🇷🇺",
    code: "RU",
    dialCode: "7",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Rwanda",
    nameAr: 'رواندا',
    flag: "🇷🇼",
    code: "RW",
    dialCode: "250",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Reunion",
    nameAr: 'لا ريونيون',
    flag: "🇷🇪",
    code: "RE",
    dialCode: "262",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Saint Barthelemy",
    nameAr: 'سان بارتيلمي',
    flag: "🇧🇱",
    code: "BL",
    dialCode: "590",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    nameAr: 'سانت هيلانة وأسينشين وتريستان دا كونا',
    flag: "🇸🇭",
    code: "SH",
    dialCode: "290",
    minLength: 4,
    maxLength: 4,
  ),
  AppIntlCountry(
    name: "Saint Kitts and Nevis",
    nameAr: 'سانت كيتس ونيفيس',
    flag: "🇰🇳",
    code: "KN",
    dialCode: "1869",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Saint Lucia",
    nameAr: 'سانت لوسيا',
    flag: "🇱🇨",
    code: "LC",
    dialCode: "1758",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Saint Martin",
    nameAr: 'سانت مارتن',
    flag: "🇲🇫",
    code: "MF",
    dialCode: "590",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Saint Pierre and Miquelon",
    nameAr: 'سان بيير وميكلون',
    flag: "🇵🇲",
    code: "PM",
    dialCode: "508",
    minLength: 6,
    maxLength: 6,
  ),
  AppIntlCountry(
    name: "Saint Vincent and the Grenadines",
    nameAr: 'سانت فينسنت والغرينادين',
    flag: "🇻🇨",
    code: "VC",
    dialCode: "1784",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Samoa",
    nameAr: 'ساموا',
    flag: "🇼🇸",
    code: "WS",
    dialCode: "685",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "San Marino",
    nameAr: 'سان مارينو',
    flag: "🇸🇲",
    code: "SM",
    dialCode: "378",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Sao Tome and Principe",
    nameAr: 'ساو تومي وبرينسيب',
    flag: "🇸🇹",
    code: "ST",
    dialCode: "239",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Saudi Arabia",
    nameAr: 'المملكة العربية السعودية',
    flag: "🇸🇦",
    code: "SA",
    dialCode: "966",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Senegal",
    nameAr: 'السنغال',
    flag: "🇸🇳",
    code: "SN",
    dialCode: "221",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Serbia",
    nameAr: 'صربيا',
    flag: "🇷🇸",
    code: "RS",
    dialCode: "381",
    minLength: 12,
    maxLength: 12,
  ),
  AppIntlCountry(
    name: "Seychelles",
    nameAr: 'سيشل',
    flag: "🇸🇨",
    code: "SC",
    dialCode: "248",
    minLength: 6,
    maxLength: 6,
  ),
  AppIntlCountry(
    name: "Sierra Leone",
    nameAr: 'سيراليون',
    flag: "🇸🇱",
    code: "SL",
    dialCode: "232",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Singapore",
    nameAr: 'سنغافورة',
    flag: "🇸🇬",
    code: "SG",
    dialCode: "65",
    minLength: 12,
    maxLength: 12,
  ),
  AppIntlCountry(
    name: "Slovakia",
    nameAr: 'سلوفاكيا',
    flag: "🇸🇰",
    code: "SK",
    dialCode: "421",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Slovenia",
    nameAr: 'سلوفينيا',
    flag: "🇸🇮",
    code: "SI",
    dialCode: "386",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Solomon Islands",
    nameAr: 'جزر سليمان',
    flag: "🇸🇧",
    code: "SB",
    dialCode: "677",
    minLength: 5,
    maxLength: 5,
  ),
  AppIntlCountry(
    name: "Somalia",
    nameAr: 'الصومال',
    flag: "🇸🇴",
    code: "SO",
    dialCode: "252",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "South Africa",
    nameAr: 'جنوب أفريقيا',
    flag: "🇿🇦",
    code: "ZA",
    dialCode: "27",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "South Sudan",
    nameAr: 'جنوب السودان',
    flag: "🇸🇸",
    code: "SS",
    dialCode: "211",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "South Georgia and the South Sandwich Islands",
    nameAr: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
    flag: "🇬🇸",
    code: "GS",
    dialCode: "500",
    minLength: 15,
    maxLength: 15,
  ),
  AppIntlCountry(
    name: "Spain",
    nameAr: 'أسبانيا',
    flag: "🇪🇸",
    code: "ES",
    dialCode: "34",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Sri Lanka",
    nameAr: 'سريلانكا',
    flag: "🇱🇰",
    code: "LK",
    dialCode: "94",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Sudan",
    nameAr: 'السودان',
    flag: "🇸🇩",
    code: "SD",
    dialCode: "249",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Suriname",
    nameAr: 'سورينام',
    flag: "🇸🇷",
    code: "SR",
    dialCode: "597",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Svalbard and Jan Mayen",
    nameAr: 'سفالبارد ويان ماين',
    flag: "🇸🇯",
    code: "SJ",
    dialCode: "47",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Eswatini",
    nameAr: 'إسواتيني',
    flag: "🇸🇿",
    code: "SZ",
    dialCode: "268",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Sweden",
    nameAr: 'السويد',
    flag: "🇸🇪",
    code: "SE",
    dialCode: "46",
    minLength: 13,
    maxLength: 13,
  ),
  AppIntlCountry(
    name: "Switzerland",
    nameAr: 'سويسرا',
    flag: "🇨🇭",
    code: "CH",
    dialCode: "41",
    minLength: 12,
    maxLength: 12,
  ),
  AppIntlCountry(
    name: "Syrian Arab Republic",
    nameAr: 'سوريا',
    flag: "🇸🇾",
    code: "SY",
    dialCode: "963",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Taiwan",
    nameAr: 'تايوان',
    flag: "🇹🇼",
    code: "TW",
    dialCode: "886",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Tajikistan",
    nameAr: 'طاجيكستان',
    flag: "🇹🇯",
    code: "TJ",
    dialCode: "992",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Tanzania, United Republic of Tanzania",
    nameAr: 'تنزانيا',
    flag: "🇹🇿",
    code: "TZ",
    dialCode: "255",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Thailand",
    nameAr: 'تايلاند',
    flag: "🇹🇭",
    code: "TH",
    dialCode: "66",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Timor-Leste",
    nameAr: 'تيمور الشرقية',
    flag: "🇹🇱",
    code: "TL",
    dialCode: "670",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Togo",
    nameAr: 'توغو',
    flag: "🇹🇬",
    code: "TG",
    dialCode: "228",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Tokelau",
    nameAr: 'توكيلاو',
    flag: "🇹🇰",
    code: "TK",
    dialCode: "690",
    minLength: 4,
    maxLength: 4,
  ),
  AppIntlCountry(
    name: "Tonga",
    nameAr: 'تونغا',
    flag: "🇹🇴",
    code: "TO",
    dialCode: "676",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Trinidad and Tobago",
    nameAr: 'ترينيداد وتوباغو',
    flag: "🇹🇹",
    code: "TT",
    dialCode: "1868",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Tunisia",
    nameAr: 'تونس',
    flag: "🇹🇳",
    code: "TN",
    dialCode: "216",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Turkey",
    nameAr: 'تركيا',
    flag: "🇹🇷",
    code: "TR",
    dialCode: "90",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Turkmenistan",
    nameAr: 'تركمانستان',
    flag: "🇹🇲",
    code: "TM",
    dialCode: "993",
    minLength: 8,
    maxLength: 8,
  ),
  AppIntlCountry(
    name: "Turks and Caicos Islands",
    nameAr: 'جزر توركس وكايكوس',
    flag: "🇹🇨",
    code: "TC",
    dialCode: "1649",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Tuvalu",
    nameAr: 'توفالو',
    flag: "🇹🇻",
    code: "TV",
    dialCode: "688",
    minLength: 6,
    maxLength: 6,
  ),
  AppIntlCountry(
    name: "Uganda",
    nameAr: 'أوغندا',
    flag: "🇺🇬",
    code: "UG",
    dialCode: "256",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Ukraine",
    nameAr: 'أوكرانيا',
    flag: "🇺🇦",
    code: "UA",
    dialCode: "380",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "United Arab Emirates",
    nameAr: 'الإمارات العربية المتحدة',
    flag: "🇦🇪",
    code: "AE",
    dialCode: "971",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "United Kingdom",
    nameAr: 'المملكة المتحدة',
    flag: "🇬🇧",
    code: "GB",
    dialCode: "44",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "United States",
    nameAr: 'الولايات المتحدة الأمريكية',
    flag: "🇺🇸",
    code: "US",
    dialCode: "1",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Uruguay",
    nameAr: 'الأوروغواي',
    flag: "🇺🇾",
    code: "UY",
    dialCode: "598",
    minLength: 11,
    maxLength: 11,
  ),
  AppIntlCountry(
    name: "Uzbekistan",
    nameAr: 'أوزبكستان',
    flag: "🇺🇿",
    code: "UZ",
    dialCode: "998",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Vanuatu",
    nameAr: 'فانواتو',
    flag: "🇻🇺",
    code: "VU",
    dialCode: "678",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Venezuela, Bolivarian Republic of Venezuela",
    nameAr: 'فنزويلا',
    flag: "🇻🇪",
    code: "VE",
    dialCode: "58",
    minLength: 10,
    maxLength: 10,
  ),
  AppIntlCountry(
    name: "Vietnam",
    nameAr: 'فيتنام',
    flag: "🇻🇳",
    code: "VN",
    dialCode: "84",
    minLength: 11,
    maxLength: 11,
  ),
  AppIntlCountry(
    name: "Virgin Islands, British",
    nameAr: 'جزر العذراء البريطانية',
    flag: "🇻🇬",
    code: "VG",
    dialCode: "1284",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Virgin Islands, U.S.",
    nameAr: 'جزر العذراء الأمريكية',
    flag: "🇻🇮",
    code: "VI",
    dialCode: "1340",
    minLength: 7,
    maxLength: 7,
  ),
  AppIntlCountry(
    name: "Wallis and Futuna",
    nameAr: 'واليس وفوتونا',
    flag: "🇼🇫",
    code: "WF",
    dialCode: "681",
    minLength: 6,
    maxLength: 6,
  ),
  AppIntlCountry(
    name: "Yemen",
    nameAr: 'اليمن',
    flag: "🇾🇪",
    code: "YE",
    dialCode: "967",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Zambia",
    nameAr: 'زامبيا',
    flag: "🇿🇲",
    code: "ZM",
    dialCode: "260",
    minLength: 9,
    maxLength: 9,
  ),
  AppIntlCountry(
    name: "Zimbabwe",
    nameAr: 'زيمبابوي',
    flag: "🇿🇼",
    code: "ZW",
    dialCode: "263",
    minLength: 9,
    maxLength: 9,
  ),
];

class AppIntlCountry {
  final String name;
  final String nameAr;
  final String flag;
  final String code;
  final String dialCode;
  final String regionCode;
  final int minLength;
  final int maxLength;

  const AppIntlCountry({
    required this.name,
    required this.nameAr,
    required this.flag,
    required this.code,
    required this.dialCode,
    required this.minLength,
    required this.maxLength,
    this.regionCode = "",
  });

  String get fullCountryCode {
    return this.dialCode + this.regionCode;
  }

  String get displayCC {
    if (this.regionCode != "") {
      return "${this.dialCode} ${this.regionCode}";
    }
    return this.dialCode;
  }
}
